version: '3.8'
services:
  github-organization-invitation-api:
    container_name: github-organization-invitation-api
    image: github-org-invite-api:latest
    build: .
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '15000:15000'
    volumes:
      - ./index.js:/app/index.js
